#!/bin/sh

# Logs dir
mkdir -p /var/log/vpnserver/security_log
mkdir -p /var/log/vpnserver/packet_log
mkdir -p /var/log/vpnserver/server_log

ln -s /var/log/vpnserver/*_log /usr/local/vpnserver/

exec /usr/local/vpnserver/vpnserver execsvc

exit $?